  /* ===================== CONFIGURACIÓN DEL SITIO ===================== */
  var CFG = {
    logoUrl: '',                 // URL del logotipo completo (PNG/SVG). Vacío = isotipo incrustado + wordmark.
    whatsapp: '528113638885',    // WhatsApp con lada país
    phone: '81 3376 0911',
    email: 'ventas@logatech.com.mx',
    currency: 'MXN',
    /* Rutas de las páginas. Para WordPress cambia cada valor por el slug real, ej. catalogo:'/catalogo/' */
    pages: { inicio:'inicio.html', catalogo:'catalogo.html', producto:'producto.html', nosotros:'nosotros.html', marcas:'marcas.html', servicio:'servicio-tecnico.html', envios:'envios-y-credito.html', contacto:'contacto.html' }
  };

  /* ===================== CATEGORÍAS (cuestionario A3.1 / A3.2) ===================== */
  var CATEGORIES = [
    {id:'pruebas-rapidas',name:'Pruebas rápidas',short:'Diagnóstico inmunocromatográfico en minutos.',art:'cassette',photo:'cat_pr',subs:['Enfermedades infecciosas','Hepáticas','Tumorales e inflamatorias','Fertilidad','Vectoriales','Resistencia a antibióticos','Sepsis','Salud general']},
    {id:'antidoping',name:'Antidoping',short:'Pruebas de drogas en orina y saliva.',art:'cup',photo:'cat_ad',subs:['Pruebas individuales en orina','Frasco integrado','Cassette individual','Paneles y frascos multidrogas','Pruebas en saliva']},
    {id:'point-of-care',name:'Point of care',short:'Resultados junto al paciente.',art:'kit',photo:'cat_eq',subs:['Química seca','Turbidimetría','HbA1c','Monitoreo portátil','Coagulación']},
    {id:'cuidados-criticos',name:'Cuidados críticos',short:'Gasometría, electrolitos y marcadores cardiacos.',art:'kit',photo:'hospital',subs:['Multiparamétrico','Cardio y sepsis','Electrolitos','Gasometría']},
    {id:'deteccion-alcohol',name:'Detección de alcohol',short:'Alcoholímetros profesionales, personales y fijos.',art:'cup',photo:'empresa',subs:['Alcoholímetros profesionales','Alcoholímetros personales','Alcoholímetros fijos de pared','Pruebas rápidas','Mantenimiento y servicio técnico']},
    {id:'reactivos',name:'Reactivos',short:'Química analítica, tinciones y soluciones.',art:'bottle',photo:'cat_re',subs:['Buffers y soluciones valoradas','Colorantes','Equipos de tinción','Detergentes y limpieza especializada','Solventes y sales','Aguas','Antibacteriales','Soluciones glucosadas','Patrones de absorción atómica']},
    {id:'diagnostico-molecular',name:'Diagnóstico molecular',short:'PCR, secuenciación y extracción.',art:'kit',photo:'lab',subs:['PCR tiempo real','Secuenciación','INNO-LiPA','Extracción de ARN/ADN','Termociclador']},
    {id:'microbiologia',name:'Microbiología',short:'Medios de cultivo, agares y consumibles.',art:'bottle',photo:'cat_re',subs:['Medios de cultivo','Peptonas y agares','Biología molecular','Equipos automáticos y semiautomáticos','Consumibles']},
    {id:'equipos',name:'Equipos para diagnóstico clínico',short:'Analizadores nuevos, de fábrica, con instalación.',art:'kit',photo:'cat_eq',subs:['Química','Hematología','Coagulación','Electrolitos','Uroanálisis']},
    {id:'consumibles',name:'Consumibles y toma de muestra',short:'Tubos, contenedores, cajas Petri, portaobjetos e hisopos.',art:'tube',photo:'scientist',subs:['Tubos de toma de muestra','Contenedores de orina','Cajas Petri','Portaobjetos','Medios de transporte']}
  ];
  var CAT_HOME = ['pruebas-rapidas','antidoping','reactivos','equipos']; // las 4 destacadas en inicio

  /* ===================== MARCAS (cuestionario A5.1) ===================== */
  var BRANDS = ['MCD LAB','HYCEL','JALMEK','BD','FERMONT','COPAN','YAMATO','GH MEDICAL','Thermo Scientific','Eppendorf','VELAB','CERTUM','SD Biosensor','Instant View','ARTRON','Life Lock','Dräger','Sentech','Mission','ELITech Group','Voule','MNCHIP','Maglumi','Corning','Wiener Lab','Spinreact','Bio-Rad','Falcon','Licon','Leica','Simport','QuidelOrtho','Alfa','CerTest','Vircell','Dymind','Diagon','GeneProof','i-SENS','Immunostics','Response Biomedical','Sugentech','bioMérieux'];
  var BRANDS_HOME = ['BD','Thermo Scientific','Eppendorf','Corning','Bio-Rad','Leica','Dräger','bioMérieux','MCD LAB','HYCEL','JALMEK','COPAN','CERTUM','SD Biosensor','ARTRON','Spinreact','Wiener Lab','QuidelOrtho','Maglumi','Mission','Sugentech','GH MEDICAL','FERMONT','YAMATO'];

  /* ===================== PRODUCTOS (cuestionario A4.1: los más vendidos) =====================
     Campos: id, name, brand, sku, cat (id de categoría), sub, art (ilustración de respaldo), img (foto Pexels),
     badge, pres (presentación), price (null = cotización), cold (cadena de frío), bullets, specs, desc.
     Las especificaciones son de referencia: validar contra la ficha técnica del fabricante. */
  var PRODUCTS = [
    {id:'DOA164',name:'Panel multidrogas 6 parámetros en cassette',brand:'CERTUM',sku:'DOA164',cat:'antidoping',sub:'Paneles y frascos multidrogas',art:'cup',img:8670147,badge:'Más vendido',pres:'Caja con 25 pruebas',price:null,cold:false,home:true,
      bullets:['Detecta THC, COC, AMP, MET, OPI y BZO en orina en un solo paso.','Resultado visual en 5 minutos; válido hasta 10 minutos.','Ideal para reclutamiento y selección de personal, clínicas y hospitales.','Sensibilidad de corte conforme a lineamientos SAMHSA.','Registro sanitario COFEPRIS vigente.'],
      specs:{'Muestra':'Orina','Parámetros':'THC 50 · COC 300 · AMP 1000 · MET 1000 · OPI 2000 · BZO 300 ng/mL','Tiempo de lectura':'5 minutos','Presentación':'Caja con 25 cassettes + pipetas','Almacenamiento':'2–30 °C','Vida de anaquel':'24 meses'},
      desc:'Prueba inmunocromatográfica rápida para la detección cualitativa simultánea de seis drogas de abuso en orina humana. Es la prueba más solicitada por empresas con procesos de reclutamiento, clínicas de salud ocupacional y hospitales.'},
    {id:'DOA154',name:'Panel multidrogas 5 parámetros en cassette',brand:'CERTUM',sku:'DOA154',cat:'antidoping',sub:'Paneles y frascos multidrogas',art:'cup',img:8670147,badge:'',pres:'Caja con 25 pruebas',price:null,cold:false,
      bullets:['Detecta THC, COC, AMP, MET y BZO en orina.','Resultado en 5 minutos, lectura visual.','Formato cassette con pipeta incluida.'],
      specs:{'Muestra':'Orina','Parámetros':'THC · COC · AMP · MET · BZO','Tiempo de lectura':'5 minutos','Presentación':'Caja con 25','Almacenamiento':'2–30 °C'},
      desc:'Panel de cinco parámetros para programas de control de drogas en empresas y clínicas. Misma plataforma que el panel de 6 parámetros, con el perfil más usado en reclutamiento.'},
    {id:'A04-17-140-A',name:'Panel multidrogas 5 parámetros',brand:'ARTRON',sku:'A04-17-140-A',cat:'antidoping',sub:'Paneles y frascos multidrogas',art:'cup',img:8670147,badge:'',pres:'Caja con 25 pruebas',price:null,cold:false,
      bullets:['Cinco drogas en una sola prueba de orina.','Resultado en 5 minutos.','Marca canadiense con distribución autorizada.'],
      specs:{'Muestra':'Orina','Parámetros':'5 (THC, COC, AMP, MET, OPI)','Tiempo':'5 minutos','Presentación':'Caja con 25'},
      desc:'Panel multidrogas ARTRON de 5 parámetros, alternativa de alta rotación para clínicas y empresas que requieren volumen.'},
    {id:'HDOA-334',name:'Panel multidrogas 3 parámetros (THC/COC/AMP)',brand:'CERTUM',sku:'HDOA-334',cat:'antidoping',sub:'Paneles y frascos multidrogas',art:'cup',img:8670147,badge:'',pres:'Caja con 25 pruebas',price:null,cold:false,
      bullets:['Marihuana, cocaína y anfetaminas en una sola prueba.','Resultado en 5 minutos.','Formato económico para tamizaje.'],
      specs:{'Muestra':'Orina','Parámetros':'THC 50 · COC 300 · AMP 1000 ng/mL','Tiempo':'5 minutos','Presentación':'Caja con 25'},
      desc:'Panel básico de tres parámetros para tamizaje de drogas en orina.'},
    {id:'A04-15-140-A',name:'Panel multidrogas 3 parámetros (COC/AMP/THC)',brand:'ARTRON',sku:'A04-15-140-A',cat:'antidoping',sub:'Paneles y frascos multidrogas',art:'cup',img:8670147,badge:'',pres:'Caja con 25 pruebas',price:null,cold:false,
      bullets:['Tres parámetros en cassette.','Resultado en 5 minutos.','Alta disponibilidad.'],
      specs:{'Muestra':'Orina','Parámetros':'COC · AMP · THC','Tiempo':'5 minutos','Presentación':'Caja con 25'},
      desc:'Panel ARTRON de tres parámetros para programas de tamizaje de bajo costo.'},
    {id:'DTH-101',name:'Detección de marihuana (THC 50 ng/mL) en tiras',brand:'CERTUM',sku:'DTH-101',cat:'antidoping',sub:'Pruebas individuales en orina',art:'cassette',img:7280977,badge:'',pres:'Caja con 50 tiras',price:null,cold:false,
      bullets:['Prueba individual en tira reactiva.','Corte de 50 ng/mL.','Resultado en 5 minutos.'],
      specs:{'Muestra':'Orina','Analito':'THC 50 ng/mL','Formato':'Tira','Presentación':'Caja con 50'},
      desc:'Tira individual para detección cualitativa de cannabinoides en orina.'},
    {id:'DCO-101',name:'Detección de cocaína (COC 300 ng/mL) en tiras',brand:'CERTUM',sku:'DCO-101',cat:'antidoping',sub:'Pruebas individuales en orina',art:'cassette',img:7280977,badge:'',pres:'Caja con 50 tiras',price:null,cold:false,
      bullets:['Prueba individual en tira.','Corte de 300 ng/mL.','Resultado en 5 minutos.'],
      specs:{'Muestra':'Orina','Analito':'COC 300 ng/mL','Formato':'Tira','Presentación':'Caja con 50'},
      desc:'Tira individual para detección cualitativa de cocaína (benzoilecgonina) en orina.'},
    {id:'DME-101',name:'Detección de metanfetamina (MET 1000 ng/mL)',brand:'CERTUM',sku:'DME-101',cat:'antidoping',sub:'Pruebas individuales en orina',art:'cassette',img:7280977,badge:'',pres:'Caja con 50 tiras',price:null,cold:false,
      bullets:['Prueba individual en tira.','Corte de 1000 ng/mL.','Resultado en 5 minutos.'],
      specs:{'Muestra':'Orina','Analito':'MET 1000 ng/mL','Formato':'Tira','Presentación':'Caja con 50'},
      desc:'Tira individual para detección cualitativa de metanfetamina en orina.'},
    {id:'DAM-101',name:'Detección de anfetamina (AMP 1000 ng/mL)',brand:'CERTUM',sku:'DAM-101',cat:'antidoping',sub:'Pruebas individuales en orina',art:'cassette',img:7280977,badge:'',pres:'Caja con 50 tiras',price:null,cold:false,
      bullets:['Prueba individual en tira.','Corte de 1000 ng/mL.','Resultado en 5 minutos.'],
      specs:{'Muestra':'Orina','Analito':'AMP 1000 ng/mL','Formato':'Tira','Presentación':'Caja con 50'},
      desc:'Tira individual para detección cualitativa de anfetamina en orina.'},

    {id:'CAGD025E',name:'SGTi-flex COVID-19 / Influenza A+B Ag Duo',brand:'Sugentech',sku:'CAGD025E',cat:'pruebas-rapidas',sub:'Enfermedades infecciosas',art:'cassette',img:7867251,badge:'',pres:'Caja con 25 pruebas',price:null,cold:false,home:true,
      bullets:['Detección simultánea de antígeno SARS-CoV-2 e Influenza A/B en un solo cassette.','Muestra nasofaríngea; resultado en 15 minutos.','Alta sensibilidad y especificidad validada clínicamente.','Incluye hisopos, tubos de extracción y tapas gotero.'],
      specs:{'Muestra':'Hisopado nasofaríngeo','Tiempo':'15 minutos','Presentación':'25 pruebas + accesorios','Almacenamiento':'2–30 °C','Registro':'COFEPRIS'},
      desc:'Prueba combinada para diferenciar COVID-19 de Influenza A y B en una sola corrida, reduciendo el costo por paciente y el tiempo de respuesta en urgencias y consulta externa.'},
    {id:'166561',name:'Prueba rápida Influenza Ag A/B/A(H1N1) pandémica',brand:'SD Biosensor',sku:'166561',cat:'pruebas-rapidas',sub:'Enfermedades infecciosas',art:'cassette',img:7867251,badge:'',pres:'Caja con 25 pruebas',price:null,cold:false,
      bullets:['Diferencia Influenza A, B y A(H1N1) pandémica.','Muestra nasofaríngea; resultado en 10–15 minutos.','Marca SD con distribución autorizada.'],
      specs:{'Muestra':'Hisopado nasofaríngeo','Tiempo':'10–15 minutos','Presentación':'Caja con 25','Almacenamiento':'2–30 °C'},
      desc:'Prueba de antígeno para influenza con diferenciación de subtipo pandémico, de uso frecuente en temporada invernal.'},
    {id:'FHC-201',name:'Embarazo Combo (hCG 25 mIU/mL) orina/suero en tiras',brand:'CERTUM',sku:'FHC-201',cat:'pruebas-rapidas',sub:'Fertilidad',art:'cassette',img:7280977,badge:'',pres:'Caja con 50 tiras',price:null,cold:false,
      bullets:['Detección de hCG en orina o suero.','Sensibilidad 25 mIU/mL.','Resultado en 3–5 minutos.'],
      specs:{'Muestra':'Orina / suero','Sensibilidad':'25 mIU/mL','Tiempo':'3–5 minutos','Presentación':'Caja con 50'},
      desc:'Tira combo para detección temprana de embarazo en laboratorio clínico y consultorio.'},
    {id:'IDEC-425',name:'Dengue Combo Duo IgG/IgM + NS1 en cassette',brand:'CERTUM',sku:'IDEC-425',cat:'pruebas-rapidas',sub:'Vectoriales',art:'cassette',img:7280977,badge:'Temporada',pres:'Caja con 25 pruebas',price:null,cold:false,home:true,
      bullets:['Antígeno NS1 y anticuerpos IgG/IgM en el mismo cassette.','Muestra de sangre total, suero o plasma.','Resultado en 15 minutos.','Cobertura desde el día 1 de síntomas hasta fase tardía.'],
      specs:{'Muestra':'Sangre total / suero / plasma','Tiempo':'15 minutos','Presentación':'25 cassettes + buffer','Almacenamiento':'2–30 °C','Registro':'COFEPRIS'},
      desc:'Permite diagnosticar dengue en cualquier fase de la infección con una sola muestra, ideal para hospitales y laboratorios en zonas endémicas.'},
    {id:'02-7602',name:'Prueba de sangre oculta en heces (FOB) en cassette',brand:'Instant View',sku:'02-7602',cat:'pruebas-rapidas',sub:'Salud general',art:'cassette',img:7867251,badge:'',pres:'Caja con 25 pruebas',price:null,cold:false,
      bullets:['Detección inmunológica de hemoglobina humana en heces.','Sin restricciones dietéticas previas.','Resultado en 5 minutos.'],
      specs:{'Muestra':'Heces','Tiempo':'5 minutos','Presentación':'Caja con 25','Almacenamiento':'2–30 °C'},
      desc:'Prueba inmunocromatográfica para tamizaje de sangrado gastrointestinal, usada en chequeos de salud general.'},

    {id:'368171',name:'Tubo Vacutainer® EDTA K2, tapa lila, 4 ml',brand:'BD',sku:'368171',cat:'consumibles',sub:'Tubos de toma de muestra',art:'tube',img:4047146,badge:'Pedido recurrente',pres:'Caja con 100 tubos',price:null,cold:false,home:true,
      bullets:['Anticoagulante EDTA K2 en aerosol para hematología.','Tubo de plástico PET con tapa Hemogard™ de seguridad.','Volumen de extracción 4 ml, 13 × 75 mm.','Compatible con todos los analizadores de hematología.','Original BD, distribuidor autorizado.'],
      specs:{'Aditivo':'EDTA K2 7.2 mg','Volumen':'4 ml','Dimensiones':'13 × 75 mm','Material':'PET','Presentación':'Caja con 100 · Empaque con 1,000'},
      desc:'Los tubos BD Vacutainer® con EDTA K2 son el estándar para toma de muestra en hematología y banco de sangre. Uno de los consumibles de compra recurrente más frecuentes entre hospitales y cadenas de laboratorio.'},
    {id:'368175',name:'Tubo Vacutainer® SST™ tapa amarilla, 5 ml, suero con gel separador',brand:'BD',sku:'368175',cat:'consumibles',sub:'Tubos de toma de muestra',art:'tube',img:6622518,badge:'',pres:'Caja con 100 tubos',price:null,cold:false,
      bullets:['Activador de coagulación y gel separador.','Suero listo para química clínica e inmunología.','Tapa Hemogard™ de seguridad.'],
      specs:{'Aditivo':'Activador de coágulo + gel','Volumen':'5 ml','Dimensiones':'13 × 100 mm','Presentación':'Caja con 100'},
      desc:'Tubo para obtención de suero con barrera de gel, de uso diario en química clínica.'},
    {id:'BD-ROJO-6ML',name:'Tubo Vacutainer® tapa roja, 6 ml, suero con activador de coagulación',brand:'BD',sku:'Por confirmar',cat:'consumibles',sub:'Tubos de toma de muestra',art:'tube',img:4047146,badge:'',pres:'Caja con 100 tubos',price:null,cold:false,
      bullets:['Activador de coagulación con sílice, sin gel.','Suero para serología, banco de sangre y química.','Tapa Hemogard™ de seguridad.'],
      specs:{'Aditivo':'Activador de coágulo','Volumen':'6 ml','Dimensiones':'13 × 100 mm','Presentación':'Caja con 100'},
      desc:'Tubo de suero sin gel para pruebas que requieren muestra sin barrera. La clave del cuestionario coincide con la del tubo amarillo; confirmar con el cliente.'},
    {id:'CY-151PZA',name:'Contenedor para muestra de orina no estéril',brand:'GH MEDICAL',sku:'CY-151PZA',cat:'consumibles',sub:'Contenedores de orina',art:'cup',img:8670147,badge:'',pres:'Pieza',price:null,cold:false,
      bullets:['Contenedor de polipropileno con tapa de rosca.','Uso general en laboratorio clínico.','Alta rotación y disponibilidad constante.'],
      specs:{'Material':'Polipropileno','Esterilidad':'No estéril','Presentación':'Pieza / bolsa'},
      desc:'Contenedor económico para recolección de orina en laboratorio y hospital.'},
    {id:'BK-25031',name:'Vaso para orina 120 ml, tapa roja, no ensamblado, no estéril',brand:'GH MEDICAL',sku:'BK-25031',cat:'consumibles',sub:'Contenedores de orina',art:'cup',img:8670147,badge:'',pres:'Bolsa con 100',price:null,cold:false,
      bullets:['Capacidad 120 ml con graduación.','Tapa roja a rosca no ensamblada.','Ideal para alto volumen de muestras.'],
      specs:{'Capacidad':'120 ml','Tapa':'Roja, rosca','Esterilidad':'No estéril','Presentación':'Bolsa con 100'},
      desc:'Vaso recolector de orina de uso rutinario, no estéril, para laboratorios con alto flujo.'},
    {id:'BK-25032E-MX',name:'Vaso para orina 120 ml, tapa roja, estéril con etiqueta',brand:'GH MEDICAL',sku:'BK-25032E-MX',cat:'consumibles',sub:'Contenedores de orina',art:'cup',img:8670147,badge:'',pres:'Pieza empacada individualmente',price:null,cold:false,
      bullets:['Estéril, empaque individual.','Etiqueta para identificación del paciente.','Para urocultivo y antidoping con cadena de custodia.'],
      specs:{'Capacidad':'120 ml','Tapa':'Roja, rosca','Esterilidad':'Estéril','Presentación':'Pieza'},
      desc:'Vaso estéril con etiqueta para muestras que requieren condiciones controladas, como urocultivo.'},
    {id:'PETRI-100',name:'Caja Petri sencilla estéril 100 × 15 mm',brand:'LOGA',sku:'PETRI',cat:'consumibles',sub:'Cajas Petri',art:'bottle',img:8940346,badge:'',pres:'Paquete con 20 · Caja con 500',price:null,cold:false,
      bullets:['Poliestireno cristal, estéril por radiación.','Compatible con medios MCD LAB.','Marca propia Loga con precio competitivo.'],
      specs:{'Dimensiones':'100 × 15 mm','Material':'Poliestireno','Esterilidad':'Estéril','Presentación':'20 / 500'},
      desc:'Caja Petri desechable para microbiología clínica e industrial.'},
    {id:'2947BN-25X75',name:'Portaobjetos 25 × 75 mm, banda esmerilada, grosor 0.90–1.10 mm',brand:'Corning',sku:'2947BN-25X75',cat:'consumibles',sub:'Portaobjetos',art:'kit',img:3938022,badge:'',pres:'Caja con 72 piezas',price:null,cold:false,
      bullets:['Vidrio de alta claridad con banda esmerilada para rotular.','Bordes lisos, grosor uniforme.','Marca Corning, distribuidor autorizado.'],
      specs:{'Dimensiones':'25 × 75 mm','Grosor':'0.90–1.10 mm','Banda':'Esmerilada','Presentación':'Caja con 72'},
      desc:'Portaobjetos de vidrio para frotis, citología y microscopía de rutina.'},
    {id:'COP111C',name:'Tubo con medio de transporte Stuart con hisopo',brand:'COPAN',sku:'COP111C',cat:'consumibles',sub:'Medios de transporte',art:'tube',img:8442652,badge:'',pres:'Caja con 100',price:null,cold:false,
      bullets:['Medio Stuart para conservación de muestras bacteriológicas.','Hisopo estéril incluido.','Marca COPAN, referencia mundial en toma de muestra.'],
      specs:{'Medio':'Stuart','Hisopo':'Incluido','Esterilidad':'Estéril','Presentación':'Caja con 100'},
      desc:'Sistema de transporte para cultivos bacterianos desde la toma hasta el laboratorio.'},

    {id:'PT7494',name:'Agar sangre con azida',brand:'MCD LAB',sku:'PT7494',cat:'microbiologia',sub:'Peptonas y agares',art:'bottle',img:3786246,badge:'',pres:'Frasco de 450 g',price:null,cold:false,
      bullets:['Medio selectivo para Gram positivos (estreptococos, estafilococos).','Fabricación nacional con control por lote.','Certificado de análisis disponible.'],
      specs:{'Presentación':'Frasco 450 g','Rendimiento':'~10 L','Almacenamiento':'10–30 °C, lugar seco','Uso':'Aislamiento de Gram positivos'},
      desc:'Medio de cultivo deshidratado con azida de sodio para inhibir Gram negativos.'},
    {id:'PT7114',name:'Agar MacConkey',brand:'MCD LAB',sku:'PT7114',cat:'microbiologia',sub:'Medios de cultivo',art:'bottle',img:3786246,badge:'',pres:'Frasco de 450 g',price:null,cold:false,home:true,
      bullets:['Medio selectivo y diferencial para enterobacterias.','Fabricación nacional con control de calidad por lote.','Rinde aproximadamente 9 litros de medio.','Certificado de análisis disponible.'],
      specs:{'Presentación':'Frasco 450 g','Rendimiento':'~9 L','pH final':'7.1 ± 0.2','Almacenamiento':'10–30 °C, lugar seco','Uso':'Aislamiento de Gram negativos'},
      desc:'El medio de cultivo de mayor rotación en microbiología clínica para aislamiento y diferenciación de bacilos entéricos Gram negativos.'},

    {id:'64840',name:'Kit Wright, equipo de tinción con buffer',brand:'HYCEL',sku:'64840',cat:'reactivos',sub:'Equipos de tinción',art:'kit',img:8539753,badge:'',pres:'Kit completo',price:null,cold:false,home:true,
      bullets:['Colorante Wright + buffer de fosfatos listo para usar.','Tinción de frotis sanguíneos y médula ósea.','Coloración nítida de núcleos y granulaciones.','Fabricado en México por HYCEL.'],
      specs:{'Contenido':'Colorante Wright 500 ml + Buffer 500 ml','Uso':'Hematología · Citología','Almacenamiento':'15–30 °C','Presentación':'Kit'},
      desc:'Equipo de tinción Wright para la evaluación morfológica de células sanguíneas. El kit de tinción más pedido por laboratorios clínicos en toda la República.'},
    {id:'64293',name:'Kit Ziehl Neelsen, equipo para tinción BAAR',brand:'HYCEL',sku:'64293',cat:'reactivos',sub:'Equipos de tinción',art:'kit',img:8539753,badge:'',pres:'Kit completo',price:null,cold:false,
      bullets:['Fucsina fenicada, alcohol-ácido y azul de metileno.','Tinción de bacilos ácido-alcohol resistentes.','Listo para usar.'],
      specs:{'Contenido':'3 reactivos','Uso':'Microbiología · Tuberculosis','Almacenamiento':'15–30 °C','Presentación':'Kit'},
      desc:'Equipo de tinción para identificación de micobacterias en frotis.'},
    {id:'64287-100',name:'Aceite de inmersión tipo A',brand:'HYCEL',sku:'64287-100',cat:'reactivos',sub:'Colorantes',art:'bottle',img:11703173,badge:'',pres:'Frasco de 100 ml',price:null,cold:false,
      bullets:['Índice de refracción óptimo para objetivos 100×.','Baja viscosidad, no amarillea.','Frasco gotero.'],
      specs:{'Tipo':'A','Presentación':'100 ml','Uso':'Microscopía'},
      desc:'Aceite de inmersión para microscopía de alta resolución.'},
    {id:'5342',name:'Detergente líquido Plus neutro',brand:'HYCEL',sku:'5342',cat:'reactivos',sub:'Detergentes y limpieza especializada',art:'bottle',img:11703173,badge:'',pres:'Garrafa de 4 L',price:null,cold:false,
      bullets:['Limpieza de material de vidrio y plástico de laboratorio.','pH neutro, libre de fosfatos.','Enjuague fácil, sin residuos.'],
      specs:{'pH':'Neutro','Presentación':'4 L','Uso':'Lavado de material'},
      desc:'Detergente concentrado para material de laboratorio.'},
    {id:'1822',name:'Alcohol etílico (etanol) 96%',brand:'HYCEL',sku:'1822',cat:'reactivos',sub:'Solventes y sales',art:'bottle',img:11703173,badge:'',pres:'Garrafa de 20 L',price:null,cold:false,
      bullets:['Etanol al 96% para uso en laboratorio.','Desinfección, extracción y preparación de soluciones.','Disponible en varias presentaciones.'],
      specs:{'Concentración':'96%','Presentación':'20 L (otras bajo pedido)','Grado':'Laboratorio'},
      desc:'Solvente de uso general en laboratorios clínicos e industriales.'},
    {id:'A1425-15',name:'Ácido clorhídrico 36–38% ACS, 3.5 L',brand:'JALMEK',sku:'A1425-15',cat:'reactivos',sub:'Solventes y sales',art:'bottle',img:11703173,badge:'',pres:'Frasco de 3.5 L',price:null,cold:false,
      bullets:['Grado reactivo ACS.','Para análisis químico industrial y preparación de soluciones.','Hoja de seguridad disponible.'],
      specs:{'Concentración':'36–38%','Grado':'ACS','Presentación':'3.5 L'},
      desc:'Ácido clorhídrico grado ACS para laboratorios industriales y de control de calidad.'},
    {id:'917',name:'Xilol (dimetilbenceno) 19 L',brand:'HYCEL',sku:'917',cat:'reactivos',sub:'Solventes y sales',art:'bottle',img:11703173,badge:'',pres:'Garrafa de 19 L',price:null,cold:false,
      bullets:['Aclarante para histología y citología.','Grado laboratorio.','Presentación industrial de 19 L.'],
      specs:{'Presentación':'19 L','Uso':'Histología · Patología','Grado':'Laboratorio'},
      desc:'Solvente aclarante de uso rutinario en histopatología.'},

    {id:'IISC-425',name:'BioFire® FilmArray® RP2 panel respiratorio molecular',brand:'bioMérieux',sku:'IISC-425',cat:'diagnostico-molecular',sub:'PCR tiempo real',art:'kit',img:18471457,badge:'',pres:'Caja con 30 pruebas',price:null,cold:true,
      bullets:['PCR multiplex: 21+ patógenos respiratorios en una corrida.','Resultado en aproximadamente 45 minutos.','Producto refrigerado: se embarca lunes y miércoles con cadena de frío.'],
      specs:{'Tecnología':'PCR multiplex anidada','Tiempo':'~45 minutos','Muestra':'Hisopado nasofaríngeo','Almacenamiento':'Refrigerado','Presentación':'Caja con 30'},
      desc:'Panel sindrómico respiratorio para hospitales con diagnóstico molecular. Requiere equipo FilmArray®.'}
  ];
